name:                aoc-lh
version:             0.1.0.0
github:              "mgritter/aoc-lh"
license:             BSD3
author:              "Mark Gritter"
maintainer:          "example@example.com"
copyright:           "2022 Mark Gritter"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc-lh#readme>

dependencies:
- liquidhaskell
- liquid-base
- liquid-containers
- liquid-vector
- liquid-bytestring
- sort
- split

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fplugin=LiquidHaskell

library:
  source-dirs: src
    
executables:
  day4:
    main:                Main.hs
    source-dirs:         2022/day4
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-lh

tests:
  aoc-lh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-lh
